# NUMPY

Numpy is a general-purpose array-processing package. It is a tool for working with arrays.

Array in Numpy is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. 

Number of dimension is called RANK.
An array class in Numpy is called as ndarray.
Numpy arrays are accessed by using square brackets and can be initialized by using nested Python Lists.

## Creating numpy array

#### Creating array of rank 1.

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3])
print("An array of rank 1 : \n", arr)

An array of rank 1 : 
 [1 2 3]


#### Creating array of rank 2. Two dimensional array. 

In [3]:
arr = np.array([[1,2,3],
               [4,5,6]])
print("An array of rank 2: \n", arr)

An array of rank 2: 
 [[1 2 3]
 [4 5 6]]


#### Creating an array using Tuple

In [4]:
arr = np.array((2,3,4))
print("Array created ith tuple: ", arr)

Array created ith tuple:  [2 3 4]


## Accessing arrays using index

In [5]:
# Initial an Array
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])
print("Initial Array: ")
print(arr)

Initial Array: 
[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]


#### print a range of array

In [22]:
# prints row 0 and all columns in row 0. [row(0:3), column(0:3)]
first_row = arr[:1, :]
print(first_row)

[[-1.  2.  0.  4.]]


In [23]:
# prints column 0 and and all rows of colunm 0. 
first_column = arr[:, :1]
print(first_column)

[[-1. ]
 [ 4. ]
 [ 2.6]
 [ 3. ]]


In [21]:
# prints column 0 and 1, and all rows of column 0 and 1.
first_2columns = arr[:, :2]
print(first_2columns)

[[-1.   2. ]
 [ 4.  -0.5]
 [ 2.6  0. ]
 [ 3.  -7. ]]


In [24]:
# print first 2 rows and column 0 t0 1
f2c01 = arr[:2, :2]
print(f2c01)

[[-1.   2. ]
 [ 4.  -0.5]]


In [25]:
# print first 2 rows and column 0 t0 2
f2c01 = arr[:2, :3]
print(f2c01)

[[-1.   2.   0. ]
 [ 4.  -0.5  6. ]]


In [27]:
# print first 2 rows and column 0 and 2
f2c02 = arr[:2, : :2]
print(f2c01)

[[-1.  0.]
 [ 4.  6.]]


In [29]:
# Printing elements at
# specific Indices
# to print elements at an indices, we just print the variable
# without np. i.e != np.arr when initializing array.
Index_arr = arr[[1, 1, 0, 3], 
                [3, 2, 1, 0]]
print (Index_arr)

[0. 6. 2. 3.]


### Basic array operation

In [30]:
# Python program to demonstrate
# basic operations on single array
import numpy as np
 
# Defining Array 1
a = np.array([[1, 2],
              [3, 4]])
 
# Defining Array 2
b = np.array([[4, 3],
              [2, 1]])

#### Adding and subtracting forom elements of an array

In [32]:
# Adding 1 to every element
print ("Adding 1 to every element of array 1:", a + 1)

Adding 1 to every element of array 1: [[2 3]
 [4 5]]


In [33]:
# Subtracting 2 from each element
print ("\nSubtracting 2 from each element of Array 2:", b - 2)


Subtracting 2 from each element of Array 2: [[ 2  1]
 [ 0 -1]]


### Sum of array elements and adding two arrays

In [39]:
# sum of array elements
# Performing Unary operations
print(a)
print ("\nSum of all array "
       "elements in a: ", a.sum(),"\n")
print(b)
print("\nSum of all array "
       "elements in b:",b.sum())

[[1 2]
 [3 4]]

Sum of all array elements in a:  10 

[[4 3]
 [2 1]]

Sum of all array elements in b: 10


In [42]:
# Adding two arrays
# Performing Binary operations
print ("\nThe sum of arrays a and b:\n", a + b)
print("The sum of both arrays is:", (a+b).sum())


The sum of arrays a and b:
 [[5 5]
 [5 5]]
the sum of both arrays is: 20


## Data type

In [45]:
print(arr.dtype)
print(a.dtype)
print(b.dtype)
print(f2c01.dtype)

float64
int32
int32
float64


In [46]:
# Forced Datatype
x = np.array([1, 2], dtype = np.int64)   
print("\nForcing a Datatype: ")
print(x.dtype)


Forcing a Datatype: 
int64


### Math Operations on DataType array

In [47]:
# First Array
arr1 = np.array([[4, 7], [2, 6]], 
                 dtype = np.float64)
                  
# Second Array
arr2 = np.array([[3, 6], [2, 8]], 
                 dtype = np.float64) 
 
# Addition of two Arrays
Sum = np.add(arr1, arr2)
print("Addition of Two Arrays: ")
print(Sum)
 
# Addition of all Array elements
# using predefined sum method
Sum1 = np.sum(arr1)
print("\nAddition of Array elements: ")
print(Sum1)
 
# Square root of Array
Sqrt = np.sqrt(arr1)
print("\nSquare root of Array1 elements: ")
print(Sqrt)
 
# Transpose of Array
# using In-built function 'T'
Trans_arr = arr1.T
print("\nTranspose of Array: ")
print(Trans_arr)

Addition of Two Arrays: 
[[ 7. 13.]
 [ 4. 14.]]

Addition of Array elements: 
19.0

Square root of Array1 elements: 
[[2.         2.64575131]
 [1.41421356 2.44948974]]

Transpose of Array: 
[[4. 2.]
 [7. 6.]]
